In [64]:
#importing modules
from math import *
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 21})
import scipy.stats as stats
from scipy.optimize import curve_fit,leastsq
from scipy.integrate import odeint, ode
from scipy.interpolate import interp1d
import numpy as np
import pandas
from scipy.interpolate import interp1d

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


# Södermanland	
# Sthlm

In [65]:
#Parameters
n=20
startvecka=10-4 #start week
Tmax=48 #length of prediction
pv=0.023 #fraction of infected that are admitted

rho=7*1/5.1 #latency period
gamma=7*1/5 #recovery rate

delay=3#2.5 #delay from infection to admission

In [66]:
file = pandas.read_excel('../data/statistik-covid19-inskrivna_v2.xlsx',sheet_name="Inskrivna i slutenvård")
data = [['Sthlm', 8,2389923], ['VGR', 9,1725881], ['Skåne', 10,1387650],['Östergötland',11,467095],['Jönköping',12,364750],['Södermanland',13,299101],['Uppsala',14,387628],['Gävleborg',15,287660],['Västmanland',16,277074],['Örebro',17,305726],['Norrbotten',18,249768],['Dalarna',19,287806],['Västernorrland',20,244855],['Värmland',21,282840],['Halland',22,336132],['Kalmar',23,245992],['Kronoberg',24,202163],['Västerbotten',25,273061],['Jämtland',26,130972],['Blekinge',27,159349],['Gotland',28,60106]] 
regioner = pandas.DataFrame(data, columns = ['region', 'index','population']) 
regionkod=['SE-AB','SE-O','SE-M','SE-E','SE-F','SE-D','SE-C','SE-X','SE-U','SE-T','SE-BD','SE-W','SE-Y','SE-S','SE-N','SE-H','SE-G','SE-AC','SE-Z','SE-K','SE-I']
regioner['Regionkod'] = regionkod
yta=np.array([6524,23800,10968,10559,8190,10437,5427,8504,6075,28029,18118,17519,5118,54665,97239,11165,21549,8424,2931,48935,3135]) #area of region
regioner['Area']=yta
ffall = 9*np.ones(21).astype(int) #week number when first case was recorded
regioner['Första fall'] = ffall
startvecka = ffall - 3

regioner.drop(regioner.index[[20]],inplace=True) #remove Gotland


In [67]:
print(startvecka)
regioner

[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


region  index  population Regionkod   Area  Första fall
0            Sthlm      8     2389923     SE-AB   6524            9
1              VGR      9     1725881      SE-O  23800            9
2            Skåne     10     1387650      SE-M  10968            9
3     Östergötland     11      467095      SE-E  10559            9
4        Jönköping     12      364750      SE-F   8190            9
5     Södermanland     13      299101      SE-D  10437            9
6          Uppsala     14      387628      SE-C   5427            9
7        Gävleborg     15      287660      SE-X   8504            9
8      Västmanland     16      277074      SE-U   6075            9
9           Örebro     17      305726      SE-T  28029            9
10      Norrbotten     18      249768     SE-BD  18118            9
11         Dalarna     19      287806      SE-W  17519            9
12  Västernorrland     20      244855      SE-Y   5118            9
13        Värmland     21      282840      SE-S  54665            9
14         Halland     22      336132      SE-N  97239            9
15          Kalmar     23      245992      SE-H  11165            9
16       Kronoberg     24      202163      SE-G  21549            9
17    Västerbotten     25      273061     SE-AC   8424            9
18        Jämtland     26      130972      SE-Z   2931            9
19        Blekinge     27      159349      SE-K  48935            9

In [68]:
file

Nyinskrivna i slutenvård med covid-19, antal patienter per inskrivningsvecka och region  \
0   Antal unika patienter som rapporterats till So...                                        
1                                                 NaN                                        
2                                                 NaN                                        
3                                                 NaN                                        
4                                                 NaN                                        
5                                                 NaN                                        
6                                Totalt inrapporterat                                        
7                                Rapporterande region                                        
8                                           Stockholm                                        
9                                     Västra Götaland                                        
10                                              Skåne                                        
11                                       Östergötland                                        
12                                       Södermanland                                        
13                                          Jönköping                                        
14                                          Gävleborg                                        
15                                            Uppsala                                        
16                                        Västmanland                                        
17                                         Norrbotten                                        
18                                             Örebro                                        
19                                            Dalarna                                        
20                                     Västernorrland                                        
21                                           Värmland                                        
22                                            Halland                                        
23                                             Kalmar                                        
24                                          Kronoberg                                        
25                                           Jämtland                                        
26                                       Västerbotten                                        
27                                           Blekinge                                        
28                                            Gotland                                        
29  Källa: patientregistret samt frivillig särskil...                                        
30  * Andel slutenvårdade per region av totalt för...                                        
31  ** Andel slutenvårdade per vecka av totalt för...                                        
32  *** Blekinge har ett fåtal coronasmittade som ...                                        
33         X - uppgiften har skyddats av sekretesskäl                                        
34            IU ingen uppgift om inskrivna patienter                                        

                          Unnamed: 1 Unnamed: 2  \
0                                NaN        NaN   
1                                NaN        NaN   
2                                NaN        NaN   
3   Totalt antal inskrivna patienter        NaN   
4                                NaN        NaN   
5                              Antal         %*   
6                              35057        100   
7                                NaN        NaN   
8                              13035  37.182303   
9                               5293  15.098269   
10                              3058   8.722937   
11    

In [84]:
from scipy.interpolate import interp1d

def getData(namn,ffall):
    temp=regioner.loc[regioner['region']==namn] #find the right row
    index=temp['index'].values #find the region index
    N=temp['population'].values #find population size of region
    N = int(N[0])
    R = file.iloc[index[0]] 
    R=R.replace(' ','X') #replace missing data with 0
    R=R.replace('X',0) 
    R=R.replace('IU',0) 
    
    ind = np.arange(3,len(R),2) 
    I = R.iloc[ind].values #extract admissions
    #print(I)
    #print(len(I))
    I=I[:-2] #remove last (incomplete) data point
    #print(I)
    padding = np.zeros(10-ffall+3) 
    I=np.insert(I,0,padding) 
    #print(I)
    veckor = np.arange(0,len(I),1) #create array of week numbers
    #print(veckor)
    
    return I,veckor,N


#Load Google mobility data
def loadMobility(namn,svecka):
    df = pandas.read_csv('../data/2020_SE_Region_Mobility_Report.csv') 
    temp=regioner.loc[regioner['region']==namn] 
    kod=temp['Regionkod'].values 
    temp2=df.loc[df['iso_3166_2_code']==kod[0]]
    transit=temp2['transit_stations_percent_change_from_baseline'].values 
    dagar=np.arange(46,46+len(transit))
    tv=np.ceil(dagar/7)
    
    
    gveckor=np.unique(tv)
    k=0
    Tr=np.zeros(int(max(gveckor)-min(gveckor))+1)

    for i in gveckor:
        ind=tv==i
        Tr[k]=np.mean(transit[ind])/100
        k=k+1
    for i in range(1,len(Tr)):
        if np.isnan(Tr[i]):
            Tr[i]=Tr[i-1]
    #print(Tr)
    init=0.2 #set base line travel
    Tr[0:2]=[init,init]
    #print(Tr)
    #print(gveckor)
    #print(gveckor-svecka)
    Trfkn = interp1d(gveckor-svecka,Tr,kind="linear",fill_value="extrapolate")
    #print(Tr)
    return Trfkn

In [89]:
def loadMobility_list(namn_list, svecka):
    
    Trfkn_list = dict()
    for i in namn_list:
       Trfkn_list[i] = loadMobility(i,svecka) 

    return Trfkn_list

In [90]:
namn_list = ['Sthlm','Södermanland']

In [91]:
Trfkn_list = loadMobility_list(namn_list, svecka=6) 

In [92]:
Trfkn_list 

{'Sthlm': <scipy.interpolate._interpolate.interp1d at 0x7e8976968dc0>,
 'Södermanland': <scipy.interpolate._interpolate.interp1d at 0x7e89769686e0>}

In [70]:
df

country_region_code country_region            sub_region_1  \
0                      SE         Sweden                     NaN   
1                      SE         Sweden                     NaN   
2                      SE         Sweden                     NaN   
3                      SE         Sweden                     NaN   
4                      SE         Sweden                     NaN   
...                   ...            ...                     ...   
62820                  SE         Sweden  Västra Götaland County   
62821                  SE         Sweden  Västra Götaland County   
62822                  SE         Sweden  Västra Götaland County   
62823                  SE         Sweden  Västra Götaland County   
62824                  SE         Sweden  Västra Götaland County   

                sub_region_2  metro_area iso_3166_2_code  census_fips_code  \
0                        NaN         NaN             NaN               NaN   
1                        NaN         NaN             NaN               NaN   
2                        NaN         NaN             NaN               NaN   
3                        NaN         NaN             NaN               NaN   
4                        NaN         NaN             NaN               NaN   
...                      ...         ...             ...               ...   
62820  Vårgårda Municipality         NaN             NaN               NaN   
62821  Vårgårda Municipality         NaN             NaN               NaN   
62822  Vårgårda Municipality         NaN             NaN               NaN   
62823  Vårgårda Municipality         NaN             NaN               NaN   
62824  Vårgårda Municipality         NaN             NaN               NaN   

             date  retail_and_recreation_percent_change_from_baseline  \
0      2020-02-15                                                2.0    
1      2020-02-16                                              -10.0    
2      2020-02-17                                               -4.0    
3      2020-02-18                                                0.0    
4      2020-02-19                                                3.0    
...           ...                                                ...    
62820  2020-11-16                                                NaN    
62821  2020-11-17                                                NaN    
62822  2020-11-18                                                NaN    
62823  2020-11-19                                                NaN    
62824  2020-11-20                                                NaN    

       grocery_and_pharmacy_percent_change_from_baseline  \
0                                                    0.0   
1                                                   -7.0   
2                                                   -3.0   
3                                                    0.0   
4                                                    1.0   
...                                                  ...   
62820                                                NaN   
62821                                                NaN   
62822                                                NaN   
62823                                                NaN   
62824                                                NaN   

       parks_percent_change_from_baseline  \
0                                     3.0   
1                                   -30.0   
2                                    -3.0   
3                                    13.0   
4                                    26.0   
...                                   ...   
62820                                 NaN   
62821                                 NaN   
62822                                 NaN   
62823                                 NaN   
62824                                 NaN   

       transit_stations_percent_change_from_baseline  \
0                                                4.0   
1

In [71]:
def beta(t,a,b,transit_fkn):
    return a+b*transit_fkn(t)

def dx(x,t,a,b,lag):
    x1, x2, x3, x4= x[0], x[1], x[2], x[3]
    
    dx1 =  -x1*beta(t-lag,a,b,transit_fkn)*x3/N
    dx2 = x1*beta(t-lag,a,b,transit_fkn)*x3/N - rho*x2
    dx3 = rho*x2 - gamma*x3
    dx4 = gamma*x3
    m = [dx1, dx2, dx3, dx4]
    #m = [np.float64(x[0] if isinstance(i, np.ndarray) else i) for i in m] #made this changes
    return m     
#return [dx1, dx2, dx3, dx4]

#define output from model
def pred_inlagda(t,a,b,lag):
    x0 = [N-1,0,1,0] #initial conditions
    #x0 = [x0[0][0]] + x0[1:]
    #print(x0,t,a,b )

    x = odeint(dx, x0, t,args=(a,b,lag))

    return pv*x[:,2]

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [72]:
R = 'Sthlm'
k = 0
I,veckor,N = getData(R,ffall[k])
transit_fkn=loadMobility(R,startvecka[k])

I_train=I
veckor_train=veckor
n=10
ah=np.linspace(3,10,n)
bh=np.linspace(4,10,n)

E=np.zeros((len(ah),len(bh)))
for i in range(n):
    print(i)
    for j in range(n):
        P=pred_inlagda(veckor_train,ah[i],bh[j],delay)
        E[i,j]=np.sqrt(np.sum((P-I_train)**2)/len(veckor_train))

[-0.0025     -0.02       -0.05857143 -0.03428571 -0.25142857 -0.43714286
 -0.45142857 -0.47428571 -0.52142857 -0.42428571 -0.41142857 -0.45
 -0.39285714 -0.39571429 -0.38285714 -0.30571429 -0.32285714 -0.28571429
 -0.33285714 -0.27142857 -0.35       -0.36428571 -0.35142857 -0.35285714
 -0.33714286 -0.30285714 -0.27       -0.27       -0.28142857 -0.28857143
 -0.29428571 -0.26571429 -0.26285714 -0.29714286 -0.30285714 -0.32142857
 -0.31571429 -0.36428571 -0.39142857 -0.41571429 -0.444     ]
[ 0.2         0.2        -0.05857143 -0.03428571 -0.25142857 -0.43714286
 -0.45142857 -0.47428571 -0.52142857 -0.42428571 -0.41142857 -0.45
 -0.39285714 -0.39571429 -0.38285714 -0.30571429 -0.32285714 -0.28571429
 -0.33285714 -0.27142857 -0.35       -0.36428571 -0.35142857 -0.35285714
 -0.33714286 -0.30285714 -0.27       -0.27       -0.28142857 -0.28857143
 -0.29428571 -0.26571429 -0.26285714 -0.29714286 -0.30285714 -0.32142857
 -0.31571429 -0.36428571 -0.39142857 -0.41571429 -0.444     ]
0
1
2
3
4
5


In [73]:
ah

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [74]:
optind = np.where(E == np.amin(E))
afit = ah[optind[0]]
bfit = bh[optind[1]]

print("Minimum RMSE: ",E[optind])
print("a=",afit,"b=",bfit)

Minimum RMSE:  [216.66060986]
a= [4.55555556] b= [8.66666667]


In [75]:
optind 

(array([2]), array([7]))

In [76]:
regs = pandas.read_pickle('../data/param_IC.pkl') #load initial guesses for a and b for each region
astart = regs['a'].values
bstart = regs['b'].values

In [77]:
regs

region  index  population Regionkod         a          b  \
0            Sthlm      8     2389923     SE-AB  4.759494   9.215190   
1              VGR      9     1725881      SE-O  3.848101   9.493671   
2            Skåne     10     1387650      SE-M  3.620253   8.240506   
3     Östergötland     11      467095      SE-E  3.734177   8.379747   
4        Jönköping     12      364750      SE-F  3.278481  10.050633   
5     Södermanland     13      299101      SE-D  3.734177   9.215190   
6          Uppsala     14      387628      SE-C  3.506329   6.430380   
7        Gävleborg     15      287660      SE-X  3.164557  10.746835   
8      Västmanland     16      277074      SE-U  3.506329   6.848101   
9           Örebro     17      305726      SE-T  3.392405   8.379747   
10      Norrbotten     18      249768     SE-BD  3.050633   7.126582   
11         Dalarna     19      287806      SE-W  2.936709  10.607595   
12  Västernorrland     20      244855      SE-Y  2.936709   9.632911   
13        Värmland     21      282840      SE-S  2.708861   9.075949   
14         Halland     22      336132      SE-N  2.594937  10.189873   
15          Kalmar     23      245992      SE-H  2.367089  11.164557   
16       Kronoberg     24      202163      SE-G  2.936709   6.848101   
17    Västerbotten     25      273061     SE-AC  2.936709   7.962025   
18        Jämtland     26      130972      SE-Z  2.822785   5.177215   
19        Blekinge     27      159349      SE-K  1.683544   1.278481   

             E  
0   175.235300  
1    90.821751  
2    41.357155  
3    17.383155  
4    21.330193  
5    15.531288  
6    17.883654  
7    20.700678  
8     8.616789  
9    12.290108  
10   20.612144  
11   12.126125  
12   14.101993  
13   15.011190  
14   10.442431  
15   11.887966  
16    8.579174  
17    3.422690  
18    3.902450  
19    4.670810